---
services:
  cachetf:
    image: locnh/cachetf:v0.2.0
    container_name: cachetf
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9100:9100"
    volumes:
      - ./cache:/cache
    environment:
      - GIN_MODE=release
      - PORT=8080
      - METRICS_PORT=9100
      - CACHE_DIR=/cache
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    # Uncomment if you want to run as a specific user
    # user: "1000:1000"
    # Uncomment to limit resources
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 512M
